#
# Author: Johnny
# Date  : 2019/7/1
#

version: '2'

networks:
  byfn:

services:
  fabric-ca-server:
    image: hyperledger/fabric-ca
    container_name: fabric-ca-server
    ports:
      - "7054:7054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server 
    volumes:
      - "./fabric-ca-server:/etc/hyperledger/fabric-ca-server"
    networks:
      - byfn
